"""empty message

Revision ID: db7b9d9b8dc6
Revises: a2a43761cc92
Create Date: 2022-11-11 23:49:54.604487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7b9d9b8dc6'
down_revision = 'a2a43761cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'updated_at')
    # ### end Alembic commands ###